---
- name: Quick benchmark
  hosts: 
    - localhost

  tasks:
    - ansible.builtin.shell: "{{ serverledge_local_bin_dir }}/serverledge-cli delete -f sieve"
      ignore_errors: True
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

    - ansible.builtin.shell: "{{ serverledge_local_bin_dir }}/serverledge-cli create -f sieve --memory 128 --src examples/sieve.js --runtime nodejs17ng --handler sieve.js"
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

    - name: Pause for 1 second
      ansible.builtin.pause:
        seconds: 1

    - ansible.builtin.shell: echo '{"Params":{},"QoSClass":0, "CanDoOffloading":true, "Async":false}' > /tmp/json

    - ansible.builtin.shell: ab -l -p /tmp/json -T application/json -c 4 -n 1000 http://{{ groups["sedge_Edge"][0] }}:1323/invoke/sieve | tee ab_output.txt
