---
- name: Install Docker
  hosts: 
    - sedge_Edge
    - sedge_Cloud

  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        append: yes
        groups: docker

    - name: reset ssh connection
      meta: reset_connection
      when: groupupdated

- name: Install Etcd
  hosts: sedge_Cloud[0]
  roles:
    - etcd



- name: Install ServerlEdge at the Edge
  hosts: sedge_Edge
  vars:
    conf_template: edge-configuration.yaml.j2

  roles:
    - serverledge

- name: Install ServerlEdge in the Cloud
  hosts: sedge_Cloud
  vars:
    conf_template: cloud-configuration.yaml.j2
  roles:
    - serverledge


- name: Install LB in the Cloud
  hosts: sedge_Cloud[-1]
  vars: 
    conf_template: lb-configuration.yaml.j2

  tasks:
    - include_role: 
        name: serverledge_lb
      when: "{{ groups['sedge_Cloud'] | length | int }} > 1"
