---
- name: Restart Serverledge
  hosts: 
    - sedge_Edge
    - sedge_Cloud
  tasks:
    - include_tasks:
        file: tasks/restart_serverledge.yml

    - name: Install CPU monitoring script
      ansible.builtin.copy:
        src: monitorCPU.sh
        dest: "{{ ansible_env.HOME }}"
        mode: '0755'

    - name: Install CPU monitoring service
      ansible.builtin.template:
        src: monitorCPU.service.j2
        dest: /etc/systemd/system/monitorCPU.service
        owner: root
        group: root
      become: yes
      register: monitor_service

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes
      when: monitor_service.changed

    - name: Start systemd service
      ansible.builtin.systemd:
        name: monitorCPU
        state: restarted
      become: yes

- name: Install and Start InfluxDb
  hosts:
    - sedge_Edge
    - sedge_Cloud
  tasks:
    - name: Stop old containers
      ansible.builtin.shell: docker stop InfluxDb
      ignore_errors: True

    - name: Start InfluxDb
      ansible.builtin.shell: docker run -d --rm -p 8086:8086 --name InfluxDb     
        -e DOCKER_INFLUXDB_INIT_MODE=setup \
        -e DOCKER_INFLUXDB_INIT_USERNAME=user \
        -e DOCKER_INFLUXDB_INIT_PASSWORD=password \
        -e DOCKER_INFLUXDB_INIT_ORG=serverledge \
        -e DOCKER_INFLUXDB_INIT_BUCKET=completions \
        -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=serverledge \
        influxdb

- name: Install and Start Solver
  hosts:
    - sedge_Cloud[0]
  tasks:
    - name: Stop old containers
      ansible.builtin.shell: docker stop Solver
      ignore_errors: True

    - name: Start Solver
      ansible.builtin.shell: docker run -d -p 2500:2500 --rm --name Solver diana0422/serverledge-solver

- name: Pull Function images from Docker hub
  hosts:
    - sedge_Edge
  tasks:
    - name: Pull imageClass function image from docker hub
      ansible.builtin.shell: docker image pull grussorusso/serverledge-imageclass
    - name: Pull serverledge-python-ffmpeg function image from docker hub
      ansible.builtin.shell: docker image pull grussorusso/serverledge-python-ffmpeg

- name: Quick benchmark
  hosts: 
    - sedge_Client
  vars:
    # MyFunction1
    func_name: myFunction # must match with the testplan
    func_mem: 128
    func_cpu: 1.0
    func_runtime: nodejs17ng
    func_handler: sieve.js
    func_src: sieve.js

    # MyFunction2
    func_name_2: myFunction2
    func_mem_2: 1000
    func_cpu_2: 3.0

    testplan: jmeter/testplanClosed2groups.jmx
    users: 3
    local_results_file: results.csv
    local_responses_file: responses.tar.gz

  tasks:
    - name: Install JMeter
      include_role:
        role: jmeter
      vars:
        jmeter_home: "{{ ansible_env.HOME }}"

    - name: Install serverledge-cli
      include_role:
        role: serverledge
      vars:
        deploy_cli_only: true

    - ansible.builtin.copy:
        src: files/sleep.py
        dest: "{{ ansible_env.HOME }}/sleep.py"

    - ansible.builtin.copy:
        src: files/sieve.js
        dest: "{{ ansible_env.HOME }}/sieve.js"

    - ansible.builtin.shell: "./serverledge/serverledge-cli delete -f {{ func_name }}"
      ignore_errors: True
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

          #- ansible.builtin.shell: "./serverledge-cli create -f myFunction --memory 128 --cpu 1.0 --src sieve.js --runtime nodejs17ng --handler sieve.js"
          #  environment:
          #    SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'
    - ansible.builtin.shell: "./serverledge/serverledge-cli create -f {{ func_name }} --memory {{ func_mem }} --cpu {{ func_cpu }} --src {{ func_src }} --runtime {{ func_runtime }} --handler {{ func_handler }}"
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

    - ansible.builtin.shell: "./serverledge/serverledge-cli delete -f {{ func_name_2 }}"
      ignore_errors: True
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

          #- ansible.builtin.shell: "./serverledge-cli create -f myFunction --memory 128 --cpu 1.0 --src sieve.js --runtime nodejs17ng --handler sieve.js"
        #  environment:
        #    SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'
    - ansible.builtin.shell: "./serverledge/serverledge-cli create -f {{ func_name_2 }} --memory {{ func_mem_2 }} --cpu {{ func_cpu_2 }} --src {{ func_src }} --runtime {{ func_runtime }} --handler {{ func_handler }}"
      environment:
        SERVERLEDGE_HOST: '{{ groups["sedge_Edge"][0] }}'

    - name: Copy testplan
      ansible.builtin.copy:
        src: "{{ testplan }}"
        dest: ./testplan.jmx

    - name: Clean previous results
      ansible.builtin.shell: "rm /tmp/jmeter*"
      ignore_errors: True

    - name: Clean previous responses
      ansible.builtin.shell: "find . -name 'jmeterResponse_*' -delete"
      ignore_errors: True

    - name: Stop any running Jmeter instance
      ansible.builtin.shell: "pgrep jmeter | xargs kill -TERM"
      ignore_errors: True

    - name: Start 
      ansible.builtin.shell: "{{ ansible_env.HOME }}/apache-jmeter-5.5/bin/jmeter -n -t ./testplan.jmx -l /tmp/jmeter_results -Jhost={{ groups['sedge_Edge'][0] }} -Jusers={{ users }}"
      async: 900
      poll: 20
      register: jmeter_out

    - name: Zip Response files
      community.general.archive:
        path:
          - jmeterResponse_*
        dest: /tmp/jmeter_responses.tar.gz
        format: gz
        remove: yes

    - name: Copy results
      ansible.builtin.fetch: 
        src: /tmp/jmeter_results
        dest: "{{ local_results_file }}"
        flat: yes

    - name: Copy responses
      ansible.builtin.fetch: 
        src: /tmp/jmeter_responses.tar.gz
        dest: "{{ local_responses_file }}"
        flat: yes

    - debug:
        var: jmeter_out.stdout_lines

- name: Get monitoring data
  hosts: 
    - sedge_Edge
    - sedge_Cloud
  vars:
    local_output_dir: "."
  tasks:
    - name: Stop systemd service
      ansible.builtin.systemd:
        name: monitorCPU
        state: stopped
      become: yes

    - name: Copy monitoring data
      ansible.builtin.fetch: 
        src: "{{ ansible_env.HOME }}/cpuUsage.txt"
        dest: "{{ local_output_dir }}/cpuUsage-{{ ansible_hostname }}.txt"
        flat: yes
