---
- name: Install Etcd
  hosts: etcd
  vars:
    app_dir: /home/{{ ansible_user }}/etcd

  tasks:
    - name: Create remote directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Download binaries
      ansible.builtin.get_url:
        url: "{{ etcd_release_url }}"
        dest: /tmp/etcd-release.tar.gz
      register: downloaded_binary

    - name: Extract binaries
      ansible.builtin.unarchive:
        src: /tmp/etcd-release.tar.gz
        remote_src: yes
        dest: "{{ app_dir }}"
      when: downloaded_binary.changed
      register: extracted_binaries

    - name: Install systemd service
      ansible.builtin.template:
        src: "templates/etcd.service.j2"
        dest: "/etc/systemd/system/myetcd.service"
        owner: root
        group: root
      become: yes
      register: changed_service

    - name: Start etcd service
      ansible.builtin.systemd:
        name: myetcd
        state: restarted
        daemon_reload: yes
      become: yes
      #when: extracted_binaries.changed or changed_service.changed

      #- name: Install Docker
      #  hosts: edge:cloud
      #  become: yes
      #  ignore_errors: true
      #  roles:
      #    - geerlingguy.docker

- name: Install ServerlEdge
  hosts: edge
  vars:
    app_dir: /home/{{ ansible_user }}/serverledge
    conf_template: templates/edge-configuration.yaml.j2

  tasks:
    - include_tasks: tasks/serverledge.yml

- name: Install ServerlEdge in the Cloud
  hosts: cloud
  vars:
    app_dir: /home/{{ ansible_user }}/serverledge
    conf_template: templates/cloud-configuration.yaml.j2

  tasks:
    - include_tasks: tasks/serverledge.yml
