---
- name: Create remote directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Copy serverledge binary
  ansible.builtin.copy:
    src: "{{ serverledge_local_bin_dir }}/serverledge"
    dest: "{{ app_dir }}/serverledge"
    mode: '0755'
  register: uploaded_binary

- name: Copy serverledge-cli binary
  ansible.builtin.copy:
    src: "{{ serverledge_local_bin_dir }}/serverledge-cli"
    dest: "{{ app_dir }}/serverledge-cli"
    mode: '0755'

- name: Install configuration file
  ansible.builtin.template:
    src: "{{ conf_template }}"
    dest: "{{ app_dir }}/conf.yml"
    owner: root
    group: root
  become: yes
  register: update_conf

- name: Install systemd service
  ansible.builtin.template:
    src: "templates/serverledge.service.j2"
    dest: "/etc/systemd/system/serverledge.service"
    owner: root
    group: root
  become: yes
  register: changed_service

- name: Kill existing serverledge containers
  ansible.builtin.shell: "docker ps | grep serverledge | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
  become: yes
  ignore_errors: True

- name: Start systemd service
  ansible.builtin.systemd:
    name: serverledge
    state: restarted
    daemon_reload: yes
  become: yes

- name: Pull nodejs image
  ansible.builtin.command: "docker pull grussorusso/serverledge-nodejs17ng"

- name: Pull Python image
  ansible.builtin.command: "docker pull grussorusso/serverledge-python310"
