---
- name: Create remote directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Copy serverledge binary
  ansible.builtin.copy:
    src: "{{ serverledge_local_bin_dir }}/serverledge"
    dest: "{{ app_dir }}/serverledge"
    mode: '0755'
  register: uploaded_binary

- name: Install configuration file
  ansible.builtin.template:
    src: "{{ conf_template }}"
    dest: "{{ app_dir }}/conf.yml"
    owner: root
    group: root
  become: yes
  register: update_conf

- name: Install systemd service
  ansible.builtin.template:
    src: "templates/serverledge.service.j2"
    dest: "/etc/systemd/system/serverledge.service"
    owner: root
    group: root
  become: yes
  register: changed_service

- name: Start systemd service
  ansible.builtin.systemd:
    name: serverledge
    state: restarted
    daemon_reload: yes
  become: yes
  when: uploaded_binary.changed or changed_service.changed or update_conf.changed

