---
- name: Create remote directory
  ansible.builtin.file:
    path: "{{ etcd_dir }}"
    state: directory
    mode: '0755'

- name: Extract binaries
  ansible.builtin.unarchive:
    src: "{{ etcd_release_url }}"
    remote_src: yes
    dest: "{{ etcd_dir }}"
  register: extract

- name: Copy etcdctl binary
  ansible.builtin.copy:
    src: "etcd/etcd-{{ etcd_version }}-linux-amd64/etcdctl"
    remote_src: yes
    dest: "/usr/local/bin/"
    mode: '0755'
  become: yes

- name: Install systemd service
  ansible.builtin.template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/myetcd.service"
    owner: root
    group: root
  become: yes
  register: systemdservice

- name: Start etcd service
  ansible.builtin.systemd:
    name: myetcd
    state: restarted
    daemon_reload: yes
  become: yes

- name: Wipe data
  ansible.builtin.shell: ETCDCTL_API=3 etcdctl del "" --from-key=true
  when: wipe_etcd
